# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: Server

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL
    # - name: Azure ACR login
    #   run: az acr login --name lifequest
    # - name: Publish container
    #   run: dotnet publish --os linux --arch x64 /t:PublishContainer -p ContainerRegistry=lifequest.azurecr.io
    - name: Publish container local
      run: dotnet publish --os linux --arch x64 /t:PublishContainer
    - name: Deploy local
      run: |
        az container create \
          --name lifequest \
          --resource-group lifequest-test \
          --image lifequest-api:latest \
          --os-type Linux \
          --cpu 1 \
          --memory 1.5 \
          --ip-address public \
          --ports 8080 \
          --environment-variables ASPNETCORE_ENVIRONMENT=Test
          --dns-name-label lifequest

    - name: Deploy resources
      run: az deployment group create --resource-group lifequest-test --parameters lifequest-test.bicepparam
      working-directory: deployment