# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  location: northeurope

jobs:
  buildServer:
    name: Build server
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: Server

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL

    #upload image
    - name: Azure ACR login
      run: az acr login --name lifequest
    - name: Publish container
      run: dotnet publish --os linux --arch x64 /t:PublishContainer -p ContainerRegistry=lifequest.azurecr.io
      #run: dotnet publish --os linux --arch x64 /t:PublishContainer -p ContainerRegistry=lifequest.azurecr.io/lifequest-api:${{ github.run_number }}
  
  deployShared:
    name: Deploy shared
    needs: buildServer
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: Deployment
    steps:
    - uses: actions/checkout@v4
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL
    # on subscription level create RGs, in identities create identities, in shared create acr + assign access, in logging create log workspace
    # - name: Deploy shared resources
    #   run: |
    #     az config set bicep.use_binary_from_path=false
    #     az deployment group create --resource-group lifequest-shared --parameters lifequest-shared.bicepparam
    - name: Deploy shared resources
      run: |
        az config set bicep.use_binary_from_path=false
        az deployment sub create --location ${{ env.location }} --parameters lifequest-setup.bicepparam

  deployEnv:
    name: Deploy Test
    needs: deployShared
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: Deployment
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL
    - name: Deploy test database
      run: |
        az config set bicep.use_binary_from_path=false
        az deployment group create --resource-group lifequest-test-db --template-file lifequest-db.bicep --parameters environment='test'
    - name: Add access to EntraId
      shell: pwsh
      run: |
        Install-Module Microsoft.Entra
        $token = (az account get-access-token --resource "https://graph.microsoft.com/" | ConvertFrom-Json).accessToken
        Connect-Entra -TenantId  ${{ secrets.AZURE_TENANT_ID }} -Scopes "Directory.Read.All", "Group.ReadWrite.All" -AccessToken $token
        $managedIdentity = Get-EntraServicePrincipal -Filter "displayName eq 'lifequest-test-db'"
        Add-EntraGroupMember -GroupId 6896d772-3988-4cae-8cd7-6ebe133ed09c -MemberId $managedIdentity.Id
    
    # - name: Add access to EntraId2
    #   shell: pwsh
    #   run: |
    #     Install-Module Microsoft.Graph.Authentication
    #     Import-Module Microsoft.Graph.Authentication
    #     Connect-MgGraph -TenantId  ${{ secrets.AZURE_TENANT_ID }} -Scopes "Directory.Read.All", "Group.ReadWrite.All" -ClientId ${{ secrets.AZURE_CLIENT_ID }}
    #     Install-Module Microsoft.Graph.Applications
    #     Import-Module Microsoft.Graph.Applications
    #     $managedIdentity = Get-MgServicePrincipal -Filter "displayName eq 'lifequest-test-db'"
    #     New-MgGroupMember -GroupId 6896d772-3988-4cae-8cd7-6ebe133ed09c -DirectoryObjectId $managedIdentity.Id
    - name: Run EF Core migrations
      working-directory: Server/LifeQuest.Api
      run: |
        ls
        dotnet tool install --global dotnet-ef
        dotnet build
        export PATH="$PATH:/home/runner/.dotnet/tools"
        dotnet ef database update -- --environment test --verbose
    # TODO: run migrations

    - name: Deploy test environment
      run: |
        az config set bicep.use_binary_from_path=false
        az deployment group create --resource-group lifequest-test --template-file lifequest-api.bicep --parameters environment='test'
  
  buildApp:
    name: Build Android app
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: Client
    steps:
    - uses: actions/checkout@v4
    - name: Install npm dependencies
      run: |
        npm install
    - name: Build Android Release
      run: |
        cd android && bash ./gradlew assembleRelease
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lifequest-app.apk
        path: android/app/build/outputs/apk/release/